# Generated by Django 3.2.8 on 2024-03-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanashapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_name', models.CharField(max_length=250)),
                ('enquiry_email', models.EmailField(max_length=250)),
                ('enquiry_subject', models.CharField(max_length=50)),
                ('enquiry_phone', models.CharField(max_length=11)),
                ('enquiry_message', models.TextField()),
            ],
        ),
    ]
